# ===================================
#  Relation Behavior Config
# ===================================

customfields:
    label: false # Could not translate in lang.php because it's not parsed in custom field creation form
    list: $/tiipiik/catalog/models/customvalue/columns.yaml
    form: $/tiipiik/catalog/models/customvalue/fields.yaml
    emptyMessage: Product has no custom field
    toolbar: 
        buttons: false
    view:
        showCheckboxes: false
