# ===================================
#  Form Behavior Config
# ===================================

name: tiipiik.catalog::lang.config.form.group_name
form: $/tiipiik/catalog/models/group/fields.yaml
modelClass: Tiipiik\Catalog\Models\Group
defaultRedirect: tiipiik/catalog/groups
create:
    title: tiipiik.catalog::lang.config.form.group_create_title
    redirect: tiipiik/catalog/groups/update/:id
    redirectClose: tiipiik/catalog/groups
update:
    title: tiipiik.catalog::lang.config.form.group_update_title
    redirect: tiipiik/catalog/groups
    redirectClose: tiipiik/catalog/groups